name: checkoutActions

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
   checkout:
       runs-on: ubuntu-22.04
       steps:
         - name: "running the current repo in the current os"
           uses: actions/checkout@main
         - name: "listing all the files in the directory"
           run : ls -al
         - name: reading the file in the repo
           run: echo hello.txt
         
