name: firstOne

on: push

jobs:
   hello:
      runs-on: ubuntu-latest
      steps:
        - name: Hello
          run:  echo "Hello Github Actions"
        - name: repo Name
          run: echo ${{ github.repository }}
        - name: branch name
          run:  echo ${{ github.ref_name }}
        - name: person name
          run: echo ${{ github.actor }}
        - name: commit sha
          run: echo ${{github.sha }}
        - name: event
          run: echo ${{ github.event_name }}
        - name: secret
          run: echo ${{ FIRST_SECRET }}
          
               
              
               
           
